# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe
{% set name = "gridmarthe" %}
{% set version = "0.0.1" %}
{% set sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" %} 

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/brgm/hydrogeological-modelling/marthe-tools/gridmarthe/-/archive/v{{ version }}/gridmarthe-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True # [py<39]
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - python                                # [build_platform != target_platform]
    - pip                                   # [build_platform != target_platform]
    - numpy >=1.22,<2.0                     # [build_platform != target_platform]
    - charset_normalizer
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - setuptools                            # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.22,<2.0                     
  run:
    - python
    - numpy
    - pandas
    - h5netcdf
    - xarray
    - geopandas
    - rasterio
    - rioxarray
    - shapely
    - matplotlib

test:
  imports:
    - {{ name }}
  requires:
    - pip
#    - pytest
#  source_files:
#    - tests
  commands:
    - pip check
    - python -c "import gridmarthe"
#    - pytest tests/test_gridmarthe.py

about:
  home: https://gitlab.com/brgm/hydrogeological-modelling/marthe-tools/gridmarthe.git
  summary: 'Simple, fast read/write Python package for MartheGrids'
  description: |
    Full support of gridmarthe read operations by wrapping MARTHE fortran read/write module,
    allowing fast reading of marthe grid file (v9, v8, constant_data, etc.), for any variable.
    Release under GNU General Public License version 3.0
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - manlaya
